find_package(GLFW3 REQUIRED)
include_directories(${GLFW3_INCLUDE_DIRS})
add_definitions(${GLFW3_DEFINITIONS})
if(NOT GLFW3_FOUND)
    message(ERROR " GLFW3 not found!")
else()
    add_definitions(-DWITH_GLFW ${GLFW3_DEFINITIONS})
    list(APPEND COMMON_LIBS ${GLFW3_LIBRARIES})
endif()
